------
# Combined Symetric Matrices


-----

----

<h4> Create 2 Symtetic Matrix </h4>

<h4> Compute Sum , Mat_mul , hadamard_mat_mul </h4>

<h4> See if the result is also symetric </h4>

----

In [2]:
import numpy as np

In [3]:
def rand():
    return int(np.abs(np.round((5*np.random.randn())+2)))


#(m,n)=(rand(),rand())


(m,n)=(4,4)



M1 = np.random.randn(m,n)
M2 = np.random.randn(m,n)



S1 = M1.T @ M1

S2 = M2.T @ M2


Add = S1+S2;

SUB = S1 - S2;

mat_mul = S1 @ S2 ;

mat_mul_h = S1*S2;


print("S1 + S2 ")
print(Add)

print("\n")

print("S1-S2 ")
print(SUB)

print("\n")

print("Hadamard product S1*S2 ")
print(mat_mul_h)

print("\n")

print("General Matrix Multiplication S1 @ S2")
print(mat_mul)
print("\n")






S1 + S2 
[[ 4.85005002  0.89801585 -0.97443783  3.57077908]
 [ 0.89801585  4.20569337 -1.77665944  2.84425917]
 [-0.97443783 -1.77665944  7.27305708 -0.8478536 ]
 [ 3.57077908  2.84425917 -0.8478536  10.30255162]]


S1-S2 
[[-2.19959155 -0.41502158 -1.28121375 -5.805393  ]
 [-0.41502158 -3.16645575  3.43508489 -3.77317642]
 [-1.28121375  3.43508489  3.09948337  2.92553453]
 [-5.805393   -3.77317642  2.92553453 -6.76781271]]


Hadamard product S1*S2 
[[ 4.67119556  0.15854739 -0.17299489 -5.23803115]
 [ 0.15854739  1.91535367 -2.16082236 -1.53676252]
 [-0.17299489 -2.16082236 10.82264053 -1.95997414]
 [-5.23803115 -1.53676252 -1.95997414 15.08482027]]


General Matrix Multiplication S1 @ S2
[[-0.58128309  1.00233067 -0.67155209 -0.39672164]
 [-0.85785715 -1.62368382  1.28966412 -2.67727835]
 [ 2.23469477 -7.76142608  6.52884913 -3.46192606]
 [ 4.20169312  0.69507927 -0.12770847  6.35005246]]




In [4]:
print("due to its non - elemental wise approch general mat mul never results in a symetric matrix  S1@S2")
print(mat_mul-mat_mul.T)

due to its non - elemental wise approch general mat mul never results in a symetric matrix  S1@S2
[[ 0.          1.86018781 -2.90624686 -4.59841476]
 [-1.86018781  0.          9.05109019 -3.37235762]
 [ 2.90624686 -9.05109019  0.         -3.33421759]
 [ 4.59841476  3.37235762  3.33421759  0.        ]]


In [5]:
print("addition and substraction of a symetric matrix always resluts in a symetric one ")
print("S1+S2")
print(Add-Add.T)
print("S1-S2")
print(SUB-SUB.T)
print("\n")
print("Hadamard Multiplication with 2 symetric matrices always result in a symetric matrix")
print(mat_mul_h-mat_mul_h.T)

addition and substraction of a symetric matrix always resluts in a symetric one 
S1+S2
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
S1-S2
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Hadamard Multiplication with 2 symetric matrices always result in a symetric matrix
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


-----
To understand why the matrix multiplication of two symmetric matrices is generally not symmetric, let's start by reviewing the properties of symmetric matrices and the operations mentioned.

### Symmetric Matrices

A matrix $ A $ is symmetric if $ A^T = A $, where $ A^T $ denotes the transpose of $ A $.

### Addition and Subtraction

If $ A $ and $ B $ are symmetric matrices, then their sum and difference are also symmetric:
$ (A + B)^T = A^T + B^T = A + B $
$ (A - B)^T = A^T - B^T = A - B $

### Hadamard (Element-wise) Multiplication

For the Hadamard product (element-wise multiplication), if \( A \) and \( B \) are symmetric:
$ (A \circ B)_{ij} = A_{ij} B_{ij} $
Since each element \( (i,j) \) corresponds directly to \( (j,i) \), the Hadamard product of two symmetric matrices is also symmetric:
$ (A \circ B)^T = A^T \circ B^T = A \circ B $
### Matrix Multiplication

Matrix multiplication, however, behaves differently. If $ A $ and $ B $ are symmetric, their product $ AB $ is generally not symmetric. To see why, consider the definition of the transpose of a product of matrices:

$ (AB)^T = B^T A^T  $

For $ AB $ to be symmetric, $ (AB)^T $ must equal $ AB $:
$ B^T A^T = AB $

Since $ A $ and $ B $ are symmetric, we know $ A^T = A $ and $ B^T = B $, so:

$ B A = AB $

For this to be true, $ A $ and $ B $ must commute, i.e., $ AB = BA $. However, in general, matrices do not commute. Thus,$ AB $ is not symmetric unless $ A $ and $ B  $ commute, which is a special case rather than the general rule.

### Example to Illustrate

Let's consider two symmetric matrices $ A $ and $ B $:

$ A = \begin{pmatrix} 1 & 2 \\ 2 & 3 \end{pmatrix}, \quad B = \begin{pmatrix} 4 & 5 \\ 5 & 6 \end{pmatrix} $

Both $ A $ and $ B $ are symmetric:

$ A^T = A, \quad B^T = B $

Now, let's compute $ AB $:

$ AB = \begin{pmatrix} 1 & 2 \\ 2 & 3 \end{pmatrix} \begin{pmatrix} 4 & 5 \\ 5 & 6 \end{pmatrix} = \begin{pmatrix} 1 \cdot 4 + 2 \cdot 5 & 1 \cdot 5 + 2 \cdot 6 \\ 2 \cdot 4 + 3 \cdot 5 & 2 \cdot 5 + 3 \cdot 6 \end{pmatrix} = \begin{pmatrix} 14 & 17 \\ 23 & 28 \end{pmatrix} $

Now compute the transpose of $ AB $:
$ (AB)^T = \begin{pmatrix} 14 & 17 \\ 23 & 28 \end{pmatrix}^T = \begin{pmatrix} 14 & 23 \\ 17 & 28 \end{pmatrix} $

Clearly,$ AB \neq (AB)^T $. Therefore, $ AB $ is not symmetric.

### Conclusion

The matrix multiplication of two symmetric matrices results in a symmetric matrix only when the two matrices commute. This condition is rare in practice, which is why the product of two symmetric matrices is generally not symmetric. In contrast, addition, subtraction, and Hadamard multiplication of symmetric matrices always yield symmetric matrices due to the element-wise nature of these operations and the properties of transposition.



-----

____

# NOTE a multiplication of symetric matrix can be a syemtric matrix when all the diagonal elememts in diagonals are constant or same

<b> for eg diag1 ={2,2,2}  diag2 = {5,5,5}  soo this combination will result into a symetric matrix always </b>

<h3> <i><b> This can have acceptions and it is not General in nature</i></b></h3>


____

In [6]:
(a,b,c,d) = (5,6,8,10)
M1 = np.array([
    # add a constant diagonal matrix
    [a, 1, 1, b],
    [1, a, b, 1],
    [1, b, a, 1],
    [b, 1, 1, a]
])

M2 = np.array([
    # add a constant diagonal matrix
    [d, 1, 1, c],
    [1, d, c, 1],
    [1, c, d, 1],
    [c, 1, 1, d]
])


M3 = M1 @ M2

print(M3-M3.T)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
