----

# Diagonal Matrix Special Property 

----

-----
When we multiply a diagonal matrix by itself using both standard matrix multiplication and the Hadamard product, the results are the same. Here's a detailed explanation of why this happens.

### Diagonal Matrix

A diagonal matrix \( D \) is a square matrix in which all the off-diagonal elements are zero. For example, a $ n \times n $ diagonal matrix \( D \) can be written as:

$ D = \begin{pmatrix}
d_1 & 0 & \cdots & 0 \\
0 & d_2 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & d_n
\end{pmatrix} $

### Standard Matrix Multiplication

When multiplying a diagonal matrix \( D \) by itself using standard matrix multiplication, we calculate the dot product of the rows of the first matrix with the columns of the second matrix.

$ D \cdot D = \begin{pmatrix}
d_1 & 0 & \cdots & 0 \\
0 & d_2 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & d_n
\end{pmatrix}
\cdot
\begin{pmatrix}
d_1 & 0 & \cdots & 0 \\
0 & d_2 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & d_n
\end{pmatrix} $

The result of this multiplication is another diagonal matrix where each diagonal element is the square of the corresponding diagonal element in \( D \):

$ D \cdot D = \begin{pmatrix}
d_1^2 & 0 & \cdots & 0 \\
0 & d_2^2 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & d_n^2
\end{pmatrix} $

### Hadamard Product

The Hadamard product is performed element-wise, so when we multiply a diagonal matrix \( D \) by itself using the Hadamard product, we also get a diagonal matrix where each element is the square of the corresponding element in \( D \):

$ D \circ D = \begin{pmatrix}
d_1 & 0 & \cdots & 0 \\
0 & d_2 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & d_n
\end{pmatrix}
\circ
\begin{pmatrix}
d_1 & 0 & \cdots & 0 \\
0 & d_2 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & d_n
\end{pmatrix} $

The result is:

$ D \circ D = \begin{pmatrix}
d_1^2 & 0 & \cdots & 0 \\
0 & d_2^2 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & d_n^2
\end{pmatrix} $
### Conclusion

In both standard matrix multiplication and the Hadamard product, multiplying a diagonal matrix by itself results in another diagonal matrix where each diagonal element is the square of the original element. This is why, in the case of diagonal matrices, these two multiplication methods yield the same result.





$ D = \begin{pmatrix}
d_1 & 0 & 0 \\
0 & d_2 & 0 \\
0 & 0 & d_3
\end{pmatrix} $

### Standard Matrix Multiplication

Standard matrix multiplication involves taking the dot product of rows and columns. When we multiply the diagonal matrix \( D \) by itself:
$ D \cdot D = \begin{pmatrix}
d_1 & 0 & 0 \\
0 & d_2 & 0 \\
0 & 0 & d_3
\end{pmatrix} \cdot \begin{pmatrix}
d_1 & 0 & 0 \\
0 & d_2 & 0 \\
0 & 0 & d_3
\end{pmatrix} $

The resulting matrix \( C \) will be:

$ C = \begin{pmatrix}
d_1 \cdot d_1 + 0 \cdot 0 + 0 \cdot 0 & d_1 \cdot 0 + 0 \cdot d_2 + 0 \cdot 0 & d_1 \cdot 0 + 0 \cdot 0 + 0 \cdot d_3 \\
0 \cdot d_1 + d_2 \cdot 0 + 0 \cdot 0 & 0 \cdot 0 + d_2 \cdot d_2 + 0 \cdot 0 & 0 \cdot 0 + d_2 \cdot 0 + 0 \cdot d_3 \\
0 \cdot d_1 + 0 \cdot 0 + d_3 \cdot 0 & 0 \cdot 0 + 0 \cdot d_2 + d_3 \cdot 0 & 0 \cdot 0 + 0 \cdot 0 + d_3 \cdot d_3
\end{pmatrix} $

Since \( D \) is a diagonal matrix, all off-diagonal elements are zero. Thus, the result simplifies to:

$ C = \begin{pmatrix}
d_1^2 & 0 & 0 \\
0 & d_2^2 & 0 \\
0 & 0 & d_3^2
\end{pmatrix} $

### Hadamard Product

The Hadamard product is the element-wise multiplication of two matrices. When we take the Hadamard product of \( D \) with itself:
$ D \circ D = \begin{pmatrix}
d_1 & 0 & 0 \\
0 & d_2 & 0 \\
0 & 0 & d_3
\end{pmatrix} \circ \begin{pmatrix}
d_1 & 0 & 0 \\
0 & d_2 & 0 \\
0 & 0 & d_3
\end{pmatrix} $

The resulting matrix \( C \) will be:
$ C = \begin{pmatrix}
d_1 \cdot d_1 & 0 \cdot 0 & 0 \cdot 0 \\
0 \cdot 0 & d_2 \cdot d_2 & 0 \cdot 0 \\
0 \cdot 0 & 0 \cdot 0 & d_3 \cdot d_3
\end{pmatrix} $

This simplifies to:

$ C = \begin{pmatrix}
d_1^2 & 0 & 0 \\
0 & d_2^2 & 0 \\
0 & 0 & d_3^2
\end{pmatrix} $

### Conclusion

For the 3x3 diagonal matrix \( D \), both the standard matrix multiplication and the Hadamard product result in the same matrix:

$ C = \begin{pmatrix}
d_1^2 & 0 & 0 \\
0 & d_2^2 & 0 \\
0 & 0 & d_3^2
\end{pmatrix} $

-----

In [2]:
import numpy as np

In [16]:
# Create 2 (4x4) matrix one "full matrix with on zero elememts" and a diagonal matrix
# Multiply each by itself (A*A) and also (A@A) and observe: Standard and Hadamard Multiplication

(m,n)=(4,4)
b=6
M1 = abs(m*(np.random.randn(m,n))+b)

Diag_mat = np.diag(np.diag(abs(m*(np.random.randn(m,n))+b)))

M1_M1 = M1@M1
Diag_Diag = Diag_mat@Diag_mat

print("M1@M1")
print(M1_M1)
print("\n")
print("diag @ diag@")
print(Diag_Diag)



M1_M1_H = M1 * M1
Diag_Diag_H = Diag_mat * Diag_mat

print("\n")
print("M1*M1: Hadamard")
print(M1_M1_H)

print("\n")

print("\n")
print("diag * diag: Hadamard")
print(Diag_Diag_H)


M1@M1
[[116.10712269  88.75793113 152.09754163 137.01107499]
 [134.16639976  74.58987535 139.12457352 159.03752902]
 [ 86.97179094  89.87440543 107.75614682 167.60812413]
 [ 90.3868679   66.54862154 100.64408659 139.7376974 ]]


diag @ diag@
[[294.07003226   0.           0.           0.        ]
 [  0.          46.85351034   0.           0.        ]
 [  0.           0.          25.08664846   0.        ]
 [  0.           0.           0.         142.46089531]]


M1*M1: Hadamard
[[8.57281108e+01 3.02421949e+00 5.96966088e+01 1.69162568e+01]
 [7.67490810e+01 4.85882577e+00 1.32219017e+01 8.73000392e+01]
 [2.26201571e-03 5.35678059e+01 5.71730628e+01 3.76771302e+01]
 [1.29074272e+01 8.90544427e+00 1.47853281e+01 7.34761682e+01]]




diag * diag: Hadamard
[[294.07003226   0.           0.           0.        ]
 [  0.          46.85351034   0.           0.        ]
 [  0.           0.          25.08664846   0.        ]
 [  0.           0.           0.         142.46089531]]
