The Hadamard product (also known as the element-wise product or the Schur product) is an operation that takes two matrices of the same dimensions and produces another matrix of the same dimensions where each element is the product of the corresponding elements in the original matrices. This operation is different from the standard matrix multiplication, which involves dot products of rows and columns.

Here's a formal definition and an example to illustrate the Hadamard product:

### Definition
Given two matrices \( A \) and \( B \) of the same dimensions $ m \times n $:

$ A = \begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix} $

$ B = \begin{bmatrix}
b_{11} & b_{12} & \cdots & b_{1n} \\
b_{21} & b_{22} & \cdots & b_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
b_{m1} & b_{m2} & \cdots & b_{mn}
\end{bmatrix} $

The Hadamard product $ C = A \circ B $ is defined as:

$ C = \begin{bmatrix}
a_{11} \cdot b_{11} & a_{12} \cdot b_{12} & \cdots & a_{1n} \cdot b_{1n} \\
a_{21} \cdot b_{21} & a_{22} \cdot b_{22} & \cdots & a_{2n} \cdot b_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} \cdot b_{m1} & a_{m2} \cdot b_{m2} & \cdots & a_{mn} \cdot b_{mn}
\end{bmatrix} $

### Example
Let's take two \( 2 \times 2 \) matrices as an example:

$ A = \begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix} $

$ B = \begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix} $

The Hadamard product $ C = A \circ B $ is calculated as follows:

$C = \begin{bmatrix}
1 \cdot 5 & 2 \cdot 6 \\
3 \cdot 7 & 4 \cdot 8
\end{bmatrix} = \begin{bmatrix}
5 & 12 \\
21 & 32
\end{bmatrix} $

Thus, the Hadamard product of  $ A $  and $ B $ is:

$ C = \begin{bmatrix}
5 & 12 \\
21 & 32
\end{bmatrix} $

### Applications
The Hadamard product is used in various fields including:
- **Signal processing**: Element-wise multiplication of signals.
- **Machine learning**: In neural networks for operations like gating mechanisms in LSTM networks.
- **Computer graphics**: Texture blending and image processing.
- **Quantum computing**: Certain operations on quantum states.

The key point is that the Hadamard product operates on matrices element-by-element, unlike the conventional matrix multiplication which involves sums of products.

In [2]:
import numpy as np;

In [151]:
(m,n) = (3,4)


M1 = np.round(5*np.random.randn(m,n))
M2 = np.round(5*np.random.randn(m,n))
print("M1 \n")
print(M1)

print("M2 \n")
print(M2)
print("\n")
def mat_mul_H(M1,M2):
  result = []
    # checking if m is  same
  if(len(M1)==len(M2)):
       # checking if n is same
    if(len(M1[0]) ==len(M2[0])):

        for i in range(len(M1)):
             C1 = M1[i]  # column iteration
             C2 = M2[i]

             C1_C2 = []
             for j in range(len(C1)):
                 C1_C2.append(C1[j]*C2[j])
             result.append(C1_C2)  

        return result      


           
    else:
         print("dimensions dont match")
         return None
  else:
       print("dimensions dont match ")
       return None
    
value = np.array(mat_mul_H(M1,M2))
print("Hadamard multiplication uisng own function ")
print(value)

print("\n")

print("hadamard_matmul using * ")

print(M1*M2)



M1 

[[ 0. 12. -0. -8.]
 [ 1. -6. -0. -3.]
 [ 2. -6. -7. -0.]]
M2 

[[-1. -6. -4. -1.]
 [-1. -9.  9. -4.]
 [ 2. 10.  1. -6.]]


Hadamard multiplication uisng own function 
[[ -0. -72.   0.   8.]
 [ -1.  54.  -0.  12.]
 [  4. -60.  -7.   0.]]


hadamard_matmul using * 
[[ -0. -72.   0.   8.]
 [ -1.  54.  -0.  12.]
 [  4. -60.  -7.   0.]]
