----

# is s(A+B) = s(A)+s(B) scalar matrix multiplication

----

In [2]:
import numpy as np;

In [3]:
m = 5
n = 5
s = np.random.randn()
A = np.random.randn(m,n)

B = np.random.randn(m,n)

A_sum_B = A + B ;

Shift1 = s*A_sum_B;
Shift2 = (s*A+s*B)
print("s*(A+B) = :",Shift1)

print("\n")

print("s*(A)+s*(B): = ",Shift2)

print("Shift1 - Shift2 :",Shift1-Shift2) # these are all zeros



s*(A+B) = : [[ 0.00018408  0.00998255  0.01129611  0.01463028  0.00695587]
 [-0.0028276   0.00778644 -0.00766068  0.01327762  0.00100749]
 [ 0.00250225  0.0130641   0.00521849 -0.00765015  0.00114554]
 [ 0.01267021 -0.01427182  0.00231133  0.00145536  0.0021115 ]
 [ 0.00705425 -0.0078438   0.01257546 -0.01228467 -0.01207574]]


s*(A)+s*(B): =  [[ 0.00018408  0.00998255  0.01129611  0.01463028  0.00695587]
 [-0.0028276   0.00778644 -0.00766068  0.01327762  0.00100749]
 [ 0.00250225  0.0130641   0.00521849 -0.00765015  0.00114554]
 [ 0.01267021 -0.01427182  0.00231133  0.00145536  0.0021115 ]
 [ 0.00705425 -0.0078438   0.01257546 -0.01228467 -0.01207574]]
Shift1 - Shift2 : [[ 3.25260652e-19  0.00000000e+00  0.00000000e+00  1.73472348e-18
   0.00000000e+00]
 [-4.33680869e-19 -8.67361738e-19  8.67361738e-19  0.00000000e+00
  -2.16840434e-19]
 [ 0.00000000e+00  0.00000000e+00 -8.67361738e-19  0.00000000e+00
  -4.33680869e-19]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00

----

<h2> Transposing the matrix in numpy </h2>

-----


In [4]:
M = np.array([
    [1,2,3],
    [2,3,4]
])
print("A : ")
print(M)
print("\n")
print("A^T :")
print(M.T)

A : 
[[1 2 3]
 [2 3 4]]


A^T :
[[1 2]
 [2 3]
 [3 4]]


----
<h2> Transposing a complex matrix </h2>

----

In [5]:
C = np.array([1+4j,3,4+2j])
print("non hermitian transpose")
print(np.transpose(C)) # not the hermitian transpose
print("\n")
print("Hermitian Transpose")
np.matrix(C).H # Hermitian transpose

non hermitian transpose
[1.+4.j 3.+0.j 4.+2.j]


Hermitian Transpose


matrix([[1.-4.j],
        [3.-0.j],
        [4.-2.j]])

In [6]:
(m,n)=(3,3)
A = np.round(5*np.random.randn(m,n))
A

array([[ 6., -3.,  1.],
       [-4., -1.,  4.],
       [-6.,  3., -7.]])

In [7]:
#Select columns 
print(A[:,0])
print(A[:,1])


[ 6. -4. -6.]
[-3. -1.  3.]


In [8]:
# select rows
print(A[0,:])
print(A[1,:])


[ 6. -3.  1.]
[-4. -1.  4.]
