----

# Demonstrating (LIVE)^T = (E^T V^T I^T L^T)


-----


In [2]:
import numpy as np

In [100]:
m = 4;
n=4;
k=4;


L = np.random.randn(m,n)
I = np.random.randn(n,m)
V = np.random.randn(m,k)
E = np.random.randn(k,n)

LIVE = np.matmul(np.matmul(L,I),np.matmul(V,E))

LIVE_T = LIVE.T;

indivisual_T_mul = np.matmul(np.matmul(E.T,V.T),np.matmul(I.T,L.T))

if(LIVE_T.all() == indivisual_T_mul.all()):
    print("(LIVE)^T = (E^T V^T I^T L^T)")
else:
    print("the computer rounding errors made the result look not equal")    

print(LIVE_T)
print("\n")
print(indivisual_T_mul)



(LIVE)^T = (E^T V^T I^T L^T)
[[-10.60762295   5.40134949  15.17149094  11.60012867]
 [  4.43957543   9.73181586   9.16763282   9.00959189]
 [ -2.74402893   8.46343189  11.87699322   9.5399655 ]
 [  3.85962253  -3.84570624  -6.55042718  -4.42607499]]


[[-10.60762295   5.40134949  15.17149094  11.60012867]
 [  4.43957543   9.73181586   9.16763282   9.00959189]
 [ -2.74402893   8.46343189  11.87699322   9.5399655 ]
 [  3.85962253  -3.84570624  -6.55042718  -4.42607499]]
