-----

# <h1> Converting a non Symetric matrix into a symetric one </h1>

-----


In [2]:
import numpy as np;


----
# Method one only applicable to Square matrix such that m x n and m = n 


<h2>then:<b>(A+A.T)*0.5 = S </b>


-----


----
<h1> Additive method S = (A+A.T)*0.5 = S </h1>


Absolutely! Let's take a square matrix A as an example:

```
A = [[1, 4],  
     [2, 3]]
```

Here, A is a 2x2 square matrix (m = n = 2).

1. **Transpose (A.T):**
   Taking the transpose of A, we swap rows and columns:

   ```
   A.T = [[1, 2],  
          [4, 3]]
   ```

2. **Addition (A + A.T):**
   Now, let's add A and A.T:

   ```
   A + A.T = [[1 + 1, 4 + 2],  
              [2 + 4, 3 + 3]]

           = [[2, 6],  
              [6, 6]]
   ```

3. **Scalar Multiplication (0.5 * (A + A.T)):**
   Finally, multiply the resulting sum by 0.5:

   ```
   0.5 * (A + A.T) = 0.5 * [[2, 6],  
                             [6, 6]]

                    = [[1, 3],  
                       [3, 3]]
   ```

As you can see, the resulting matrix is symmetric. The upper triangular elements (1 and 3) are mirrored in the lower triangular positions. This is because adding A and A.T doubles the upper triangular elements, and dividing by 2 balances it out.

This demonstrates how the formula (A + A.T) * 0.5, when applied to a square matrix A, creates a new square matrix that is symmetric. 

----



In [30]:
n = 4;


A = np.array(np.random.randn(n,n)) # Square Matrix


S = (A+ A.T)*0.5   # S is a symetric matrix


print("S is a Symetric matrix :")
print("$n")

print(S)


S is a Symetric matrix :
$n
[[-0.46100386 -0.18717632 -0.16637733 -1.84262796]
 [-0.18717632 -0.06363968 -0.3491819   0.31619895]
 [-0.16637733 -0.3491819  -1.06252383  0.08833338]
 [-1.84262796  0.31619895  0.08833338  0.70249463]]


-----

<h1> Multiplicative Identity Applicable for all type of matrices square non square </h1>

----

To explain why $( S = AA^T )$ and $( S = A^TA )$ are symmetric matrices and why $( AA^T $neq A^TA )$ in general, let's delve into the algebra and an example.</br>

 
### Symmetric Matrix Definition
A matrix $( S $) is symmetric if it is equal to its transpose, i.e., $( S^T = S )$.

### Symmetry of $( S = AA^T $)
Let  [$( A $) be an arbitrary $( m times n )$ matrix. Then $( S = AA^T ) $ is an $( m $times m $) $] matrix.

To prove that $( S )$ is symmetric:
$[ S = AA^T ]$
Take the transpose of $( S $):
$[ S^T = (AA^T)^T ]$
Using the property of the transpose of a product of matrices:
$[ (AA^T)^T = (A^T)^T A^T $]
Since the transpose of a transpose of a matrix is the matrix itself:
$[ (A^T)^T = A $]
Thus:
$[ (AA^T)^T = A A^T $]
Hence:
$[ S^T = S $]
Therefore, $( S = AA^T $) is symmetric.

### Symmetry of $( S = A^TA $)
Let $( A $) be an arbitrary $( m times n )$ matrix. Then $( S = A^TA $) is an $( n $times n $) matrix.


To prove that $( S )$ is symmetric:
$[ S = A^TA ] $
Take the transpose of $( S )$:
$[ S^T = (A^TA)^T ]$
Using the property of the transpose of a product of matrices:
$[ (A^TA)^T = (A^T)^T A^T ]$
Since the transpose of a transpose of a matrix is the matrix itself:
$[ (A^T)^T = A ]$
Thus:
$[ (A^TA)^T = A^T A ]$
Hence:
$[ S^T = S ]$
Therefore, $( S = A^TA )$ is symmetric.

### Why $( AA^T \neq A^TA )$ in General
The matrices \( AA^T \) and \( A^TA \) are generally not equal because they are of different sizes and the entries in these matrices will not correspond in a general case.

For example, let:
$ A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{pmatrix} $

Calculate \( AA^T \) and \( A^TA \):

1. $( AA^T )$:
$ AA^T = \begin{pmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{pmatrix} \begin{pmatrix} 1 & 3 & 5 \\ 2 & 4 & 6 \end{pmatrix} = \begin{pmatrix} 1 \cdot 1 + 2 \cdot 2 & 1 \cdot 3 + 2 \cdot 4 & 1 \cdot 5 + 2 \cdot 6 \\ 3 \cdot 1 + 4 \cdot 2 & 3 \cdot 3 + 4 \cdot 4 & 3 \cdot 5 + 4 \cdot 6 \\ 5 \cdot 1 + 6 \cdot 2 & 5 \cdot 3 + 6 \cdot 4 & 5 \cdot 5 + 6 \cdot 6 \end{pmatrix} $
$ = \begin{pmatrix} 1 + 4 & 3 + 8 & 5 + 12 \\ 3 + 8 & 9 + 16 & 15 + 24 \\ 5 + 12 & 15 + 24 & 25 + 36 \end{pmatrix} = \begin{pmatrix} 5 & 11 & 17 \\ 11 & 25 & 39 \\ 17 & 39 & 61 \end{pmatrix} $

2. $( A^TA )$:
$ A^TA = \begin{pmatrix} 1 & 3 & 5 \\ 2 & 4 & 6 \end{pmatrix} \begin{pmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{pmatrix} = \begin{pmatrix} 1 \cdot 1 + 3 \cdot 3 + 5 \cdot 5 & 1 \cdot 2 + 3 \cdot 4 + 5 \cdot 6 \\ 2 \cdot 1 + 4 \cdot 3 + 6 \cdot 5 & 2 \cdot 2 + 4 \cdot 4 + 6 \cdot 6 \end{pmatrix} $
$ = \begin{pmatrix} 1 + 9 + 25 & 2 + 12 + 30 \\ 2 + 12 + 30 & 4 + 16 + 36 \end{pmatrix} = \begin{pmatrix} 35 & 44 \\ 44 & 56 \end{pmatrix} $

Comparing the results:
$ AA^T = \begin{pmatrix} 5 & 11 & 17 \\ 11 & 25 & 39 \\ 17 & 39 & 61 \end{pmatrix} $
$ A^TA = \begin{pmatrix} 35 & 44 \\ 44 & 56 \end{pmatrix} $

Clearly,$( AA^T )$ and $( A^TA )$ are different in size and content, illustrating that in general, $( AA^T \neq A^TA )$.

This example demonstrates that while both $( S = AA^T )$ and $( S = A^TA )$ are symmetric matrices, they are not equal to each other except in specific cases where the dimensions of $( A )$ make them identical.


In [37]:
def rand(c):
    value = int(abs(np.round(c*np.random.randn())))
    return value;

c = 2
(m,n)=(rand(c)+1,rand(c)+1)


A = np.random.randn(m,n)


S1 = A @ A.T;

S2 = A.T @ A;

print("AA.T = S :")
print(S1)
print("\n")
print("A.TA = S :")
print(S2)

AA.T = S :
[[ 2.22934221  0.42655181 -0.23723442]
 [ 0.42655181  9.31379954 -2.43730295]
 [-0.23723442 -2.43730295  2.10730601]]


A.TA = S :
[[ 2.77539005 -0.54421844  2.59397679]
 [-0.54421844  1.72965578 -0.25715514]
 [ 2.59397679 -0.25715514  9.14540194]]
