----
# Code Chalenge

----


<b> Create "2" a 4x6 matrix of random numbers <b><br/>
<i> use a for loop to compute dot products between corresponding columns </i>

In [2]:
import numpy as np


In [13]:
import numpy as np

def CreateMatrix(m, n):
    matrix = []
    for i in range(n):
        vector_i = np.random.randn(m)
        matrix.append(vector_i)

    matrix = np.array(matrix)
    return matrix

m = 4
n = 6

matrix1 = CreateMatrix(m, n)
matrix2 = CreateMatrix(m, n)

print("Matrix 1:")
print(matrix1)
print("\n")

print("Matrix 2:")
print(matrix2)


Matrix 1:
[[-0.51422892 -0.24041495 -0.95614407 -1.29514125]
 [-0.49823398 -0.19498586 -2.37028667  0.46890452]
 [ 0.48877438 -1.82143391  0.24342879 -2.06721658]
 [ 0.1027798  -0.70956956 -0.59444229  0.04754857]
 [ 1.30805889  0.35920797 -1.09796715  0.96702898]
 [-1.76997762  0.9910317   0.20075082  0.31714123]]


Matrix 2:
[[-0.21476647  0.69820376 -1.41729139  0.61062836]
 [ 0.55430623  0.12241649  0.8066461   2.27808436]
 [-1.03191364  0.14190038  2.46701254  0.09224209]
 [ 0.9891185  -1.38577467 -0.42747041  0.07450968]
 [-1.07279336  1.93213978  1.62115587 -0.07694693]
 [-0.74158175 -1.03816259  1.40217443  0.31919118]]


In [14]:
DP = [] ## This is an vector/list of dot products of corresponding matrices


for i in range(len(matrix1)):
     DP.append(np.dot(matrix1[i],matrix2[i]))


print(DP)

[0.5068652805279678, -1.1438221412466667, -0.35297761837267777, 1.3426142476822873, -2.5636226901393853, 0.6664474204745189]
